services:
  scraper:
    build: ./sreality
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  web:
    build: ./flask
    depends_on:
      scraper:
        condition: service_completed_successfully
    ports:
      - "8080:8080"